### ISSUE TITLE
Add Constant keyword when input variable is not modified

### ISSUE THREAD

**Issue by captain-yoshi** [BurksEngineering/TcMatrix#4]
*Coming from a backgound of C++, so this might not be possible in PLC.*

I am trying to initialize a **_Vector3_** from the position component of an **_HMatrix_**. This fails to compile because the component is read only and the method _**CopyFrom**_ and  function **_Matrix_Copy_** could be written to. This could be resolved by changing the VAR_INPUT to be constant. In the mean time, I can store the component to a new vector.

```cpp
// MAIN
PROGRAM MAIN
VAR
	v : Vector3;
        Hm: HMatrix;
END_VAR
...

// Initialize v with position component from Homogenous transform matrix
v.CopyFrom(M:=Hm.Vector3Component);

// Error from compilation :
//     VAR_IN_OUT parameter 'M' of 'CopyFrom' needs variable with write access as input

// Alternate
Matrix_SubMatrix(M_Super:=Hm, M_Sub:=v, RowStart:=0, RowCount:=3, ColStart:=3, ColCount:=1);
```

Every function/method that does not change an input should be marked as constant. For e.g. :

```cpp
// Matrix.CopyFrom
METHOD PUBLIC CopyFrom : BOOL//Returns true if the prerequisites were met and the data was copied, false otherwise
VAR_INPUT CONSTANT
	M : REFERENCE TO Matrix;//Source of the copy operation
END_VAR
...

CopyFrom := Matrix_Copy(M,THIS^);
```

Thanks for the awesome library by the way :)

**Comment by BurksEngineering** [comment]
I definitely run into this frustration myself when using the library (wanting to 'chain' functions/properties but getting blocked by an input needing to be writeable). I usually tackle the problem by adding more helper functions that let me do a few steps at once! (Like I did this winter: https://github.com/BurksEngineering/TcTransform/commit/9e19d6dc0cf481b0c764877fd2c9c8a82fe38139)

I was about to tell you that this can't be done....but after some searching I found that twincat does support "VAR_IN_OUT CONSTANT" and it works exactly as you described! I had never heard of that option before - thank you for bringing it to my attention! 

One thing I don't know how to do is deal with the fact that all of the VAR_INPUT 'REFERENCE TO' parameters are being secretly transformed into VAR_IN_OUT parameters by the compiler. I like using the REFERENCE TO feature because i think it makes all of the nuance of working with pointers a little more visible to the typical PLC program (who doesn't normally work with pointers or think about byref vs byval parameters). 

Let me do some experimenting to see if I can adjust the library to make all of my read-only REFERENCE TO function inputs work as a constant input...

**Comment by captain-yoshi** [comment]
That would be great 👍 

**_This is a follow up question_**

Can we return a Constant Reference in TwinCAT ?

From my limited understanding, I guess we can't. The closest thing I have managed is to return a reference and it is up to the user to modify it or not.

**Comment by BurksEngineering** [comment]
Hanging on to pointers from other services can be super dangerous in PLCs. Things like online changes can make your pointer invalid without any warning! I tend to only use references or pointers if I know that they were created on the same program cycle that they are consumed (and sometimes this means re-initializing the same pointer *every cycle* just to make sure it didn't change on me)

I'll keep you posted on the VAR_IN_OUT CONSTANT thing, but it might take a while for me to find the time. Feel free to experiment on your own and submit a PR!

**Comment by BurksEngineering** [comment]
I left the TcTransform library alone because they all use byval inputs already (because the underlying matrices are fixed and can be used with ':=' assignment). Hopefully this makes using the library a little bit easier for you!
