### ISSUE TITLE
How to use this library in codesys?

### ISSUE THREAD

**Issue by zapplelove** [BurksEngineering/TcMatrix#7]

**Comment by BurksEngineering** [comment]
I don't think it is directly compatible (you can't just download the binary and put it somewhere). But the individual source files of the library are in the PlcOpen XML format, so you should be able to find a way to import them (or at least copy/paste!) into codesys.

Unfortunately I have never used the codesys IDE so I don't know the specifics of what you would have to do in order to create a library there. Good luck, and if you find there are syntax differences feel free to make a branch of this repo for codesys compatability!
